"""initial index hand

Revision ID: b793d107a5dc
Revises: 792040769256
Create Date: 2025-05-04 02:29:10.413862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b793d107a5dc'
down_revision: Union[str, None] = '792040769256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hand_scan_class_index', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['hand_scan_class_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hand_scan_class_index')
    # ### end Alembic commands ###
